### PR TITLE
added web push topic option

### PR DESCRIPTION
**Pull request by UncleUgl**

### CODE REVIEW

**Comment by UncleUgl** [comment]
@Alegrowin will you accept?

**Comment by Alegrowin** [comment]
@UncleUgl Looking at this right now! 

Thank you for your contribution

**Comment by Alegrowin** [comment]
@UncleUgl I'll merge and bump versions to generate the nuget.

Thanks

**Comment by Alegrowin** [comment]
Package should be available soon.  :rocket: 

Cheers!

**Pull request merged**
